server:
  port: 8888
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 182.92.11.233:8848
    gateway:
      routes: #数组形式
        - id: order-service  #路由唯一标识
#          uri: http://127.0.0.1:8000  #想要转发到的地址
          uri: lb://xdclass-order-service #从nacos根据服务名获取ip，lb为负载均衡
          order: 1 #优先级，数字越小优先级越高
          predicates: #断言 配置哪个路径才转发
            - Path=/order-server/**
          filters: #过滤器，请求在传递过程中通过过滤器修改
            - StripPrefix=1  #去掉第一层前缀

      discovery:
        locator:
          enabled: true