server:
  port: 8000
spring:
  application:
    name: xdclass-order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: guo960113
#nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: 182.92.11.233:8848
# 控制台输出sql、下划线转驼峰
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#负载均衡策略调整 常用：RoundRobinRule轮询 RandomRule随机 WeightedResponseTimeRule权重
xdclass-video-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
